const $=id=>document.getElementById(id);
const accountList=$("accountList"),accountCount=$("accountCount"),primaryStatus=$("primaryStatus"),pageMessage=$("pageMessage"),sheet=$("accountSheet"),form=$("accountForm"),sheetTitle=$("sheetTitle"),saveButton=$("saveButton"),saveHint=$("saveHint"),accountId=$("accountId"),bankName=$("bankName"),bankCode=$("bankCode"),accountNumber=$("accountNumber"),accountHolderName=$("accountHolderName"),isDefault=$("isDefault"),deleteSheet=$("deleteSheet"),confirmDeleteButton=$("confirmDeleteButton");
let currentSession=null,accounts=[],pendingDeleteId=null;
function esc(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function mask(v){const s=String(v||"").replace(/\s+/g,"");return !s?"":s.length<=4?s:`•••• ${s.slice(-4)}`}
function norm(v){return String(v||"").replace(/[^\d]/g,"")}
function msg(t,type="error"){pageMessage.textContent=t;pageMessage.className=`page-message ${type}`}
function clearMsg(){pageMessage.textContent="";pageMessage.className="page-message"}
async function requireLogin(){const {data,error}=await window.adaajaSupabase.auth.getSession();if(error)throw error;currentSession=data.session||null;if(!currentSession?.user){localStorage.setItem("redirectAfterLogin","bank-account.html");location.replace("login.html");return null}return currentSession}
function render(){accountCount.textContent=String(accounts.length);primaryStatus.textContent=accounts.some(x=>x.is_default)?"Tersedia":"Belum ada";if(!accounts.length){accountList.innerHTML=`<div class="empty-state"><span class="empty-state-icon"><svg viewBox="0 0 24 24"><path d="M3 10h18"/><path d="M5 10v8M9 10v8M15 10v8M19 10v8"/><path d="M4 18h16"/><path d="M12 3 3 7h18l-9-4Z"/></svg></span><strong>Belum ada rekening pencairan</strong><p>Tambahkan rekening bank agar saldo AdaPay dapat dicairkan.</p><button type="button" data-action="add">Tambah rekening</button></div>`;return}accountList.innerHTML=accounts.map(a=>`<article class="account-card ${a.is_default?"primary":""}"><div class="account-card-top"><span class="account-bank-icon"><svg viewBox="0 0 24 24"><path d="M3 10h18"/><path d="M5 10v8M9 10v8M15 10v8M19 10v8"/><path d="M4 18h16"/><path d="M12 3 3 7h18l-9-4Z"/></svg></span><span class="account-copy"><small>${a.is_default?"REKENING UTAMA":"REKENING PENCAIRAN"}</small><strong>${esc(a.bank_name||a.bank_code)}</strong><span>${esc(a.account_holder_name)} · ${esc(mask(a.account_number))}</span></span>${a.is_verified?`<span class="verified-mark"><svg viewBox="0 0 24 24"><path d="m5 12 4 4 10-10"/></svg></span>`:""}</div><div class="account-actions"><button class="default-button" type="button" data-action="default" data-id="${a.id}" ${a.is_default?"disabled":""}>${a.is_default?"Rekening utama":"Jadikan utama"}</button><button class="edit-button" type="button" data-action="edit" data-id="${a.id}">Edit rekening</button><button class="delete-button" type="button" data-action="delete" data-id="${a.id}"><svg viewBox="0 0 24 24"><path d="M4 7h16"/><path d="M9 7V4h6v3"/><path d="M7 7l1 13h8l1-13"/></svg></button></div></article>`).join("")}
async function loadAccounts(){const s=currentSession||await requireLogin();if(!s?.user)return;const {data,error}=await window.adaajaSupabase.from("seller_bank_accounts").select("*").eq("seller_id",s.user.id).order("is_default",{ascending:false}).order("created_at",{ascending:true});if(error)throw error;accounts=data||[];render()}
function resetForm(){form.reset();accountId.value="";sheetTitle.textContent="Tambah rekening";saveHint.textContent="Pastikan data sudah benar"}
function openSheet(a=null){clearMsg();if(!a){resetForm();if(!accounts.length)isDefault.checked=true}else{accountId.value=a.id;bankName.value=a.bank_name||"";bankCode.value=a.bank_code||"";accountNumber.value=a.account_number||"";accountHolderName.value=a.account_holder_name||"";isDefault.checked=!!a.is_default;sheetTitle.textContent="Edit rekening";saveHint.textContent="Simpan perubahan rekening"}sheet.classList.add("active");sheet.setAttribute("aria-hidden","false");document.body.classList.add("sheet-open")}
function closeSheet(){sheet.classList.remove("active");sheet.setAttribute("aria-hidden","true");document.body.classList.remove("sheet-open")}
function openDelete(id){pendingDeleteId=id;deleteSheet.classList.add("active");deleteSheet.setAttribute("aria-hidden","false");document.body.classList.add("sheet-open")}
function closeDelete(){pendingDeleteId=null;deleteSheet.classList.remove("active");deleteSheet.setAttribute("aria-hidden","true");document.body.classList.remove("sheet-open")}
async function unsetDefaults(exceptId=null){const s=currentSession||await requireLogin();let q=window.adaajaSupabase.from("seller_bank_accounts").update({is_default:false}).eq("seller_id",s.user.id).eq("is_default",true);if(exceptId)q=q.neq("id",exceptId);const {error}=await q;if(error)throw error}
async function saveAccount(e){e.preventDefault();clearMsg();const s=currentSession||await requireLogin();if(!s?.user)return;const num=norm(accountNumber.value);if(!bankName.value.trim()||!bankCode.value.trim()||!num||!accountHolderName.value.trim()){msg("Lengkapi seluruh data rekening.");return}if(num.length<5){msg("Nomor rekening belum valid.");return}saveButton.disabled=true;saveHint.textContent="Menyimpan rekening...";try{const editingId=accountId.value||null,makeDefault=!!isDefault.checked||accounts.length===0;if(makeDefault)await unsetDefaults(editingId);const payload={seller_id:s.user.id,bank_code:bankCode.value.trim().toUpperCase(),bank_name:bankName.value.trim(),account_number:num,account_holder_name:accountHolderName.value.trim(),is_default:makeDefault};let r=editingId?await window.adaajaSupabase.from("seller_bank_accounts").update(payload).eq("id",editingId).eq("seller_id",s.user.id).select().single():await window.adaajaSupabase.from("seller_bank_accounts").insert(payload).select().single();if(r.error)throw r.error;closeSheet();await loadAccounts();msg(editingId?"Rekening berhasil diperbarui.":"Rekening berhasil ditambahkan.","success")}catch(err){console.error(err);msg(err?.message||"Rekening belum dapat disimpan.")}finally{saveButton.disabled=false;saveHint.textContent="Pastikan data sudah benar"}}
async function setDefault(id){clearMsg();const s=currentSession||await requireLogin();try{await unsetDefaults(id);const {error}=await window.adaajaSupabase.from("seller_bank_accounts").update({is_default:true}).eq("id",id).eq("seller_id",s.user.id);if(error)throw error;await loadAccounts();msg("Rekening utama berhasil diperbarui.","success")}catch(err){msg(err?.message||"Rekening utama belum dapat diperbarui.")}}
async function deleteAccount(){if(!pendingDeleteId)return;const s=currentSession||await requireLogin();confirmDeleteButton.disabled=true;confirmDeleteButton.textContent="Menghapus...";try{const target=accounts.find(x=>x.id===pendingDeleteId);const {error}=await window.adaajaSupabase.from("seller_bank_accounts").delete().eq("id",pendingDeleteId).eq("seller_id",s.user.id);if(error)throw error;closeDelete();await loadAccounts();if(target?.is_default&&accounts.length)await setDefault(accounts[0].id);else msg("Rekening berhasil dihapus.","success")}catch(err){msg(err?.message||"Rekening belum dapat dihapus.")}finally{confirmDeleteButton.disabled=false;confirmDeleteButton.textContent="Hapus"}}
accountList.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;const action=b.dataset.action,id=b.dataset.id;if(action==="add")openSheet();if(action==="edit"){const a=accounts.find(x=>x.id===id);if(a)openSheet(a)}if(action==="default")setDefault(id);if(action==="delete")openDelete(id)});
$("addTopButton").onclick=()=>openSheet();$("addInlineButton").onclick=()=>openSheet();$("sheetBackdrop").onclick=closeSheet;$("closeSheetButton").onclick=closeSheet;$("deleteBackdrop").onclick=closeDelete;$("cancelDeleteButton").onclick=closeDelete;confirmDeleteButton.onclick=deleteAccount;form.onsubmit=saveAccount;accountNumber.oninput=()=>accountNumber.value=norm(accountNumber.value);
window.adaajaSupabase.auth.onAuthStateChange((event,session)=>{currentSession=session||null;if(event==="SIGNED_OUT")location.replace("login.html")});
(async()=>{try{await requireLogin();if(currentSession?.user)await loadAccounts()}catch(err){console.error(err);msg(err?.message||"Data rekening belum dapat dimuat.")}})();
