const BUCKET="product-images",COUNTER_RESPONSE_HOURS=24;
const offersList=document.getElementById("offersList"),searchInput=document.getElementById("searchInput"),sortSelect=document.getElementById("sortSelect"),statusTabs=document.getElementById("statusTabs"),resultCount=document.getElementById("resultCount"),refreshButton=document.getElementById("refreshButton"),offerSheet=document.getElementById("offerSheet"),offerSheetContent=document.getElementById("offerSheetContent"),sheetTitle=document.getElementById("sheetTitle"),counterSheet=document.getElementById("counterSheet"),responseSummary=document.getElementById("responseSummary"),newOfferPrice=document.getElementById("newOfferPrice"),newOfferHint=document.getElementById("newOfferHint"),responseMessage=document.getElementById("responseMessage"),submitNewOffer=document.getElementById("submitNewOffer"),toast=document.getElementById("toast");
let currentUser=null,offers=[],activeStatus="all",selectedOffer=null,responseOffer=null,realtimeChannel=null,toastTimer=null;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const money=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
function date(v){if(!v)return"-";const d=new Date(v);if(Number.isNaN(d.getTime()))return"-";return new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
const offerNo=id=>`NEG-${String(id||"").replaceAll("-","").slice(0,8).toUpperCase()}`;
const parsePrice=v=>Number(String(v||"").replace(/[^\d]/g,""))||0;
const formatPriceInput=v=>parsePrice(v)?new Intl.NumberFormat("id-ID").format(parsePrice(v)):"";
function isCounterExpired(o){if(String(o?.status||"").toLowerCase()!=="countered"||!o?.expires_at)return false;const t=new Date(o.expires_at).getTime();return Number.isFinite(t)&&t<=Date.now()}
const effectiveStatus=o=>isCounterExpired(o)?"expired":String(o?.status||"").toLowerCase();
function remainingTime(v){if(!v)return"";const end=new Date(v).getTime(),diff=end-Date.now();if(!Number.isFinite(end))return"";if(diff<=0)return"Sudah berakhir";const h=Math.floor(diff/3600000),m=Math.floor((diff%3600000)/60000);return h>0?`${h} jam ${m} menit lagi`:`${Math.max(m,1)} menit lagi`}
function statusInfo(v){return{pending:["Menunggu","status-pending"],countered:["Harga Balasan","status-countered"],accepted:["Disetujui","status-accepted"],rejected:["Ditolak","status-rejected"],expired:["Berakhir","status-ended"],cancelled:["Dibatalkan","status-ended"]}[String(v||"").toLowerCase()]||[v||"-","status-pending"]}
const statusGroup=v=>["expired","cancelled"].includes(String(v||"").toLowerCase())?"ended":String(v||"").toLowerCase();
function publicUrl(p){if(!p)return"";return window.adaajaSupabase.storage.from(BUCKET).getPublicUrl(p).data?.publicUrl||""}
function showToast(m){toast.textContent=m;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2400)}
async function requireUser(){const u=await window.AdaAjaAuth.getCurrentUser();if(!u){localStorage.setItem("redirectAfterLogin","my-offers.html");location.replace("login.html");return null}currentUser=u;return u}
function loading(){resultCount.textContent="Memuat...";offersList.innerHTML='<article class="skeleton-card shimmer"></article><article class="skeleton-card shimmer"></article><article class="skeleton-card shimmer"></article>'}
async function syncExpired(rows){const ids=(rows||[]).filter(isCounterExpired).map(o=>o.id);if(!ids.length)return;const {error}=await window.adaajaSupabase.from("offers").update({status:"expired",updated_at:new Date().toISOString()}).in("id",ids).eq("buyer_id",currentUser.id).eq("status","countered");if(error)console.warn("Expired belum tersinkron:",error)}
async function loadOffers(){const u=await requireUser();if(!u)return;loading();try{const {data:raw,error}=await window.adaajaSupabase.from("offers").select("id,product_id,buyer_id,seller_id,original_price,offered_price,counter_price,status,expires_at,created_at,updated_at").eq("buyer_id",u.id).order("created_at",{ascending:false});if(error)throw error;const rows=raw||[];await syncExpired(rows);const pids=[...new Set(rows.map(x=>x.product_id).filter(Boolean))],sids=[...new Set(rows.map(x=>x.seller_id).filter(Boolean))];const [pr,sr]=await Promise.all([pids.length?window.adaajaSupabase.from("products").select("id,name,price,unit,minimum_order,status,product_images(storage_path,sort_order,is_cover)").in("id",pids):Promise.resolve({data:[]}),sids.length?window.adaajaSupabase.from("profiles").select("id,username,full_name").in("id",sids):Promise.resolve({data:[]})]);const pm=new Map((pr.data||[]).map(p=>{const imgs=[...(p.product_images||[])].sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0)),c=imgs.find(i=>i.is_cover)||imgs[0];return[p.id,{...p,cover_path:c?.storage_path||""}]}));const sm=new Map((sr.data||[]).map(s=>[s.id,s.username||s.full_name||"Penjual AdaAja"]));offers=rows.map(o=>({...o,status:isCounterExpired(o)?"expired":o.status,product:pm.get(o.product_id)||null,seller_name:sm.get(o.seller_id)||"Penjual AdaAja"}));updateStats();renderOffers();subscribeRealtime()}catch(e){console.error(e);offersList.innerHTML=`<section class="empty-state"><strong>Negosiasi belum dapat dimuat</strong><p>${esc(e.message||"")}</p></section>`}}
function updateStats(){document.getElementById("pendingCount").textContent=offers.filter(o=>effectiveStatus(o)==="pending").length;document.getElementById("counteredCount").textContent=offers.filter(o=>effectiveStatus(o)==="countered").length;document.getElementById("acceptedCount").textContent=offers.filter(o=>effectiveStatus(o)==="accepted").length}
function filteredOffers(){const q=searchInput.value.trim().toLowerCase();let d=offers.filter(o=>(activeStatus==="all"||statusGroup(effectiveStatus(o))===activeStatus)&&(!q||[o.product?.name,o.seller_name,offerNo(o.id)].some(v=>String(v||"").toLowerCase().includes(q))));if(sortSelect.value==="oldest")d.sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));else if(sortSelect.value==="offer_high")d.sort((a,b)=>Number(b.offered_price)-Number(a.offered_price));else if(sortSelect.value==="offer_low")d.sort((a,b)=>Number(a.offered_price)-Number(b.offered_price));else d.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));return d}
function noteForOffer(o){const s=effectiveStatus(o);if(s==="countered")return["countered",`Penjual menawarkan ${money(o.counter_price)}. Respons ${remainingTime(o.expires_at)||"dalam 24 jam"}.`];return{pending:["pending","Harga Anda sedang menunggu keputusan penjual."],accepted:["accepted","Harga disetujui. Anda dapat melanjutkan ke checkout."],rejected:["rejected","Harga Anda tidak disetujui penjual."],expired:["ended","Harga balasan berakhir karena tidak direspons dalam waktu yang ditentukan."],cancelled:["ended","Negosiasi ini telah dibatalkan."]}[s]||["pending","Status negosiasi diperbarui."]}
function card(o){const s=effectiveStatus(o),[label,cls]=statusInfo(s),[noteCls,note]=noteForOffer(o),p=o.product||{},img=publicUrl(p.cover_path||"");const prices=[`<div class="price-box"><span>Harga produk</span><strong>${money(o.original_price||p.price)}</strong></div>`,`<div class="price-box accent"><span>Penawaran Anda</span><strong>${money(o.offered_price)}</strong></div>`];if(Number(o.counter_price||0)>0)prices.push(`<div class="price-box counter"><span>Harga balasan penjual</span><strong>${money(o.counter_price)}</strong></div>`);let actions="";if(s==="countered")actions=`<button class="response-primary action-accept" data-id="${esc(o.id)}">Terima ${money(o.counter_price)}</button><button class="response-blue action-counter" data-id="${esc(o.id)}">Tawar Lagi</button><button class="response-chat action-chat" data-id="${esc(o.id)}">Chat Penjual</button><button class="response-danger action-cancel" data-id="${esc(o.id)}">Tolak</button><button class="response-detail detail-button" data-id="${esc(o.id)}">Detail Negosiasi</button>`;else if(s==="accepted")actions=`<a class="response-primary full-action" href="checkout.html?offer_id=${encodeURIComponent(o.id)}">Lanjut ke Checkout</a><button class="response-detail detail-button" data-id="${esc(o.id)}">Detail Negosiasi</button>`;else if(["expired","rejected","cancelled"].includes(s))actions=`<a class="response-primary full-action" href="product-detail.html?id=${encodeURIComponent(o.product_id)}">Ajukan Penawaran Baru</a><button class="response-chat action-chat" data-id="${esc(o.id)}">Chat Penjual</button><button class="response-detail detail-button" data-id="${esc(o.id)}">Detail</button>`;else actions=`<button class="response-detail detail-button" data-id="${esc(o.id)}">Lihat Detail</button><a class="response-neutral" href="product-detail.html?id=${encodeURIComponent(o.product_id)}">Lihat Produk</a>`;const deadline=s==="countered"?`<div class="response-deadline"><span class="deadline-dot"></span><div><small>BATAS RESPONS</small><strong>${esc(remainingTime(o.expires_at)||"24 jam")}</strong></div><span>${o.expires_at?esc(date(o.expires_at)):""}</span></div>`:"";return `<article class="offer-card ${s==="countered"?"counter-focus":""}"><div class="offer-head"><div><strong class="offer-id">${esc(offerNo(o.id))}</strong><span class="offer-date">${esc(date(o.created_at))}</span></div><span class="status-badge ${cls}">${esc(label)}</span></div><div class="offer-product"><div class="offer-thumb">${img?`<img src="${esc(img)}" alt="${esc(p.name||"Produk")}">`:'<div class="offer-thumb-placeholder">Foto tidak tersedia</div>'}</div><div class="offer-copy"><h3>${esc(p.name||"Produk")}</h3><div class="seller-name">Penjual: ${esc(o.seller_name)}</div><div class="price-grid">${prices.join("")}</div></div></div>${deadline}<div class="offer-note ${noteCls}">${esc(note)}</div><div class="offer-actions response-actions">${actions}</div></article>`}
function renderOffers(){const d=filteredOffers();resultCount.textContent=`${d.length} negosiasi`;if(!d.length){offersList.innerHTML='<section class="empty-state"><strong>Belum ada negosiasi</strong><p>Saat Anda mengajukan harga, prosesnya akan tampil di sini.</p><a href="explore.html">Cari Produk</a></section>';return}offersList.innerHTML=d.map(card).join("");bindActions()}
function bindActions(){offersList.querySelectorAll(".detail-button").forEach(b=>b.onclick=()=>openOfferSheet(b.dataset.id));offersList.querySelectorAll(".action-accept").forEach(b=>b.onclick=()=>acceptCounter(b.dataset.id,b));offersList.querySelectorAll(".action-counter").forEach(b=>b.onclick=()=>openCounterSheet(b.dataset.id));offersList.querySelectorAll(".action-cancel").forEach(b=>b.onclick=()=>cancelCounter(b.dataset.id,b));offersList.querySelectorAll(".action-chat").forEach(b=>b.onclick=()=>openSellerChat(b.dataset.id,b))}
async function notify(userId,title,message,referenceId){if(!userId)return;const {error}=await window.adaajaSupabase.from("notifications").insert({user_id:userId,type:"offer",title,message,reference_id:referenceId,is_read:false});if(error)console.warn(error)}
async function acceptCounter(id,b){const o=offers.find(x=>x.id===id);if(!o||effectiveStatus(o)!=="countered")return;b.disabled=true;const old=b.innerHTML;b.textContent="Memproses...";try{const {error}=await window.adaajaSupabase.from("offers").update({status:"accepted",updated_at:new Date().toISOString()}).eq("id",o.id).eq("buyer_id",currentUser.id).eq("status","countered");if(error)throw error;await notify(o.seller_id,"Harga balasan diterima",`Pembeli menerima harga ${money(o.counter_price)} untuk ${o.product?.name||"produk"}.`,o.id);showToast(`Harga ${money(o.counter_price)} disetujui.`);await loadOffers();setTimeout(()=>location.href=`checkout.html?offer_id=${encodeURIComponent(o.id)}`,550)}catch(e){showToast(e.message||"Gagal menerima harga.");b.disabled=false;b.innerHTML=old}}
function openCounterSheet(id){responseOffer=offers.find(x=>x.id===id);if(!responseOffer||effectiveStatus(responseOffer)!=="countered")return;newOfferPrice.value="";newOfferPrice.dataset.value="";responseMessage.textContent="";responseSummary.innerHTML=`<div><span>Penawaran Anda</span><strong>${money(responseOffer.offered_price)}</strong></div><div><span>Balasan Penjual</span><strong>${money(responseOffer.counter_price)}</strong></div>`;newOfferHint.textContent=`Masukkan harga di bawah ${money(responseOffer.counter_price)} dan di atas penawaran sebelumnya.`;counterSheet.classList.add("active");counterSheet.setAttribute("aria-hidden","false");document.body.classList.add("sheet-open");requestAnimationFrame(()=>newOfferPrice.focus())}
function closeCounterSheet(){counterSheet.classList.remove("active");counterSheet.setAttribute("aria-hidden","true");document.body.classList.remove("sheet-open");responseOffer=null}
newOfferPrice.oninput=()=>{const v=parsePrice(newOfferPrice.value);newOfferPrice.dataset.value=v?String(v):"";newOfferPrice.value=formatPriceInput(v)};
submitNewOffer.onclick=async()=>{if(!responseOffer)return;const v=Number(newOfferPrice.dataset.value||0),seller=Number(responseOffer.counter_price||0),prev=Number(responseOffer.offered_price||0);responseMessage.textContent="";if(!v)return responseMessage.textContent="Masukkan harga penawaran yang benar.";if(v>=seller)return responseMessage.textContent="Harga baru harus lebih rendah dari harga balasan penjual.";if(v<=prev)return responseMessage.textContent="Harga baru harus lebih tinggi dari penawaran sebelumnya.";submitNewOffer.disabled=true;submitNewOffer.textContent="Mengirim...";try{const exp=new Date(Date.now()+COUNTER_RESPONSE_HOURS*3600000).toISOString();const {error}=await window.adaajaSupabase.from("offers").update({offered_price:v,counter_price:null,status:"pending",expires_at:exp,updated_at:new Date().toISOString()}).eq("id",responseOffer.id).eq("buyer_id",currentUser.id).eq("status","countered");if(error)throw error;await notify(responseOffer.seller_id,"Pembeli menawar lagi",`Penawaran baru ${money(v)} untuk ${responseOffer.product?.name||"produk"}.`,responseOffer.id);showToast("Penawaran baru dikirim.");closeCounterSheet();await loadOffers()}catch(e){responseMessage.textContent=e.message||"Gagal mengirim penawaran."}finally{submitNewOffer.disabled=false;submitNewOffer.textContent="Kirim Penawaran Baru"}};
async function cancelCounter(id,b){const o=offers.find(x=>x.id===id);if(!o)return;b.disabled=true;try{const {error}=await window.adaajaSupabase.from("offers").update({status:"cancelled",updated_at:new Date().toISOString()}).eq("id",o.id).eq("buyer_id",currentUser.id).eq("status","countered");if(error)throw error;await notify(o.seller_id,"Harga balasan ditolak",`Pembeli tidak melanjutkan negosiasi untuk ${o.product?.name||"produk"}.`,o.id);showToast("Negosiasi ditutup.");await loadOffers()}catch(e){showToast(e.message||"Gagal memperbarui negosiasi.");b.disabled=false}}
async function openSellerChat(id,b){const o=offers.find(x=>x.id===id);if(!o)return;b.disabled=true;const old=b.innerHTML;b.textContent="Membuka...";try{const {data,error}=await window.adaajaSupabase.rpc("get_or_create_product_conversation",{p_product_id:o.product_id,p_seller_id:o.seller_id});if(error)throw error;const cid=typeof data==="string"?data:data?.conversation_id||data?.id;if(!cid)throw new Error("Conversation ID tidak ditemukan.");location.href=`chat.html?conversation_id=${encodeURIComponent(cid)}`}catch(e){showToast(e.message||"Chat belum dapat dibuka.");b.disabled=false;b.innerHTML=old}}
function openOfferSheet(id){selectedOffer=offers.find(x=>x.id===id);if(!selectedOffer)return;const s=effectiveStatus(selectedOffer),[label]=statusInfo(s),p=selectedOffer.product||{};sheetTitle.textContent=offerNo(selectedOffer.id);offerSheetContent.innerHTML=`<div class="detail-grid"><div class="detail-card"><span>STATUS</span><strong>${esc(label)}</strong><p>Dibuat ${esc(date(selectedOffer.created_at))}</p></div><div class="detail-card"><span>PRODUK</span><strong>${esc(p.name||"Produk")}</strong></div><div class="detail-card"><span>PENJUAL</span><strong>${esc(selectedOffer.seller_name)}</strong></div><div class="detail-card"><span>HARGA PRODUK</span><strong>${money(selectedOffer.original_price||p.price)}</strong></div><div class="detail-card"><span>PENAWARAN ANDA</span><strong>${money(selectedOffer.offered_price)}</strong></div>${Number(selectedOffer.counter_price||0)>0?`<div class="detail-card emphasis-card"><span>HARGA BALASAN PENJUAL</span><strong>${money(selectedOffer.counter_price)}</strong><p>${s==="countered"?`Respons ${esc(remainingTime(selectedOffer.expires_at)||"dalam 24 jam")}.`:""}</p></div>`:""}${selectedOffer.expires_at?`<div class="detail-card"><span>BERLAKU SAMPAI</span><strong>${esc(date(selectedOffer.expires_at))}</strong></div>`:""}</div><div class="sheet-actions"><button class="secondary" id="sheetCloseAction">Tutup</button>${s==="accepted"?`<a class="primary" href="checkout.html?offer_id=${encodeURIComponent(selectedOffer.id)}">Lanjut Checkout</a>`:`<a class="blue" href="product-detail.html?id=${encodeURIComponent(selectedOffer.product_id)}">Lihat Produk</a>`}</div>`;offerSheet.classList.add("active");offerSheet.setAttribute("aria-hidden","false");document.body.classList.add("sheet-open");document.getElementById("sheetCloseAction").onclick=closeOfferSheet}
function closeOfferSheet(){offerSheet.classList.remove("active");offerSheet.setAttribute("aria-hidden","true");document.body.classList.remove("sheet-open");selectedOffer=null}
function subscribeRealtime(){if(!currentUser)return;if(realtimeChannel)window.adaajaSupabase.removeChannel(realtimeChannel);realtimeChannel=window.adaajaSupabase.channel(`buyer-offers-${currentUser.id}`).on("postgres_changes",{event:"*",schema:"public",table:"offers",filter:`buyer_id=eq.${currentUser.id}`},loadOffers).subscribe()}
searchInput.oninput=renderOffers;sortSelect.onchange=renderOffers;statusTabs.querySelectorAll("button").forEach(b=>b.onclick=()=>{activeStatus=b.dataset.status;statusTabs.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));renderOffers()});refreshButton.onclick=async()=>{refreshButton.disabled=true;await loadOffers();refreshButton.disabled=false;showToast("Negosiasi diperbarui.")};document.getElementById("offerSheetBackdrop").onclick=closeOfferSheet;document.getElementById("closeOfferSheet").onclick=closeOfferSheet;document.getElementById("counterSheetBackdrop").onclick=closeCounterSheet;document.getElementById("closeCounterSheet").onclick=closeCounterSheet;window.adaajaSupabase.auth.onAuthStateChange((e,s)=>{if(e==="SIGNED_OUT"||!s?.user)location.replace("login.html")});loadOffers();