const API_URL="https://script.google.com/macros/s/AKfycbx0VQGRZ9bXUSp8nTdgttqyD5VNOtTavrB0iqpS91gWjqTstIZzd189uIxtTQHD6FI/exec";
const box=document.getElementById("offersContainer");
let offers=[],filter="all";
function user(){try{return JSON.parse(localStorage.getItem("user")||"null")}catch{return null}}
function esc(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function money(v){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0))}
function img(url){if(!url)return"";if(url.includes("drive.google.com")){const id=url.match(/[-\w]{25,}/);if(id)return"https://drive.google.com/thumbnail?id="+id[0]+"&sz=w500"}return url}
function date(v){const d=new Date(v);return isNaN(d)?"-":new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric"}).format(d)}
function label(v){return({pending:"Menunggu",accepted:"Diterima",rejected:"Ditolak"})[v]||v}
async function api(payload){const r=await fetch(API_URL+"?t="+Date.now(),{method:"POST",redirect:"follow",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});const t=await r.text();if(!r.ok)throw new Error("HTTP "+r.status);try{return JSON.parse(t)}catch{throw new Error(t.trim().startsWith("<")?"Server mengirim HTML, bukan JSON.":"Respons server tidak valid.")}}
async function load(){const u=user();if(!u?.user_id){location.href="login.html";return}box.innerHTML='<section class="state-card"><div class="spinner"></div><strong>Memuat penawaran...</strong></section>';try{const j=await api({action:"getBuyerOffers",buyer_id:u.user_id});if(j.status!=="success"||!Array.isArray(j.offers))throw new Error(j.message||"Gagal memuat");offers=j.offers;summary();render()}catch(e){box.innerHTML=`<section class="state-card"><strong>Penawaran belum dapat dimuat</strong><span>${esc(e.message)}</span></section>`}}
function summary(){document.getElementById("pendingCount").textContent=offers.filter(x=>x.status==="pending").length;document.getElementById("acceptedCount").textContent=offers.filter(x=>x.status==="accepted").length;document.getElementById("rejectedCount").textContent=offers.filter(x=>x.status==="rejected").length}
function render(){const data=filter==="all"?offers:offers.filter(x=>x.status===filter);if(!data.length){box.innerHTML='<section class="state-card"><strong>Belum ada penawaran</strong><span>Harga yang Anda ajukan akan tampil di sini.</span></section>';return}box.innerHTML=data.map(card).join("")}
function card(o){const p=img(o.image_url||"");const photo=p?`<img src="${p}" alt="${esc(o.nama_produk)}">`:'<div class="placeholder">Foto tidak tersedia</div>';let panel="",actions="";if(o.status==="pending"){panel='<div class="status-panel pending">Penawaran sedang menunggu keputusan penjual.</div>';actions=`<div class="actions"><a class="detail" href="product-detail.html?id=${encodeURIComponent(o.product_id)}">Lihat Produk</a><a class="detail" href="product-detail.html?id=${encodeURIComponent(o.product_id)}">Batalkan Nanti</a></div>`}if(o.status==="accepted"){panel='<div class="status-panel accepted">Penawaran diterima. Anda dapat melanjutkan pembelian dengan harga ini.</div>';actions=`<div class="actions"><a class="detail" href="product-detail.html?id=${encodeURIComponent(o.product_id)}">Lihat Produk</a><a class="checkout" href="checkout.html?offer_id=${encodeURIComponent(o.offer_id)}">Lanjut Checkout</a></div>`}if(o.status==="rejected"){panel='<div class="status-panel rejected">Penawaran ditolak. Anda dapat mengajukan harga baru.</div>';actions=`<div class="actions"><a class="detail" href="product-detail.html?id=${encodeURIComponent(o.product_id)}">Lihat Produk</a><a class="checkout" href="product-detail.html?id=${encodeURIComponent(o.product_id)}">Ajukan Lagi</a></div>`}return `<article class="offer-card"><div class="offer-main"><div class="product-image">${photo}</div><div><div class="status-row"><span class="badge ${esc(o.status)}">${esc(label(o.status))}</span><span class="date">${esc(date(o.created_at))}</span></div><h2 class="product-name">${esc(o.nama_produk||"Produk")}</h2><div class="seller">Penjual: ${esc(o.seller_name||o.seller_id||"Penjual")}</div><div class="prices"><div><span>Harga produk</span><strong>${money(o.harga_asli)}</strong></div><div class="offer"><span>Harga Anda</span><strong>${money(o.harga_penawaran)}</strong></div></div></div></div>${panel}${actions}</article>`}
document.querySelectorAll(".filter-tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.status;render()});
document.getElementById("refreshButton").onclick=load;
load();