const API_URL="https://script.google.com/macros/s/AKfycbx0VQGRZ9bXUSp8nTdgttqyD5VNOtTavrB0iqpS91gWjqTstIZzd189uIxtTQHD6FI/exec";
const productId=new URLSearchParams(location.search).get("id");
const detailContent=document.getElementById("detailContent"),errorState=document.getElementById("errorState"),errorMessage=document.getElementById("errorMessage"),bottomAction=document.getElementById("bottomAction"),offerModal=document.getElementById("offerModal"),offerPrice=document.getElementById("offerPrice"),offerHint=document.getElementById("offerHint"),modalMessage=document.getElementById("modalMessage");
let currentProduct=null,currentUser=getUser();
function getUser(){try{return JSON.parse(localStorage.getItem("user")||"null")}catch{return null}}
function convertDriveImage(url){if(!url)return"";if(url.includes("drive.google.com")){const id=url.match(/[-\w]{25,}/);if(id)return"https://drive.google.com/thumbnail?id="+id[0]+"&sz=w1200"}return url}
function formatRupiah(v){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0))}
function escapeHtml(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function formatCondition(v){const m={new:"Baru, belum pernah digunakan",like_new:"Seperti baru",good:"Kondisi baik",fair:"Ada sedikit bekas pemakaian",poor:"Ada kerusakan atau noda",very_poor:"Kondisi kurang baik"};return m[v]||v||"-"}
async function loadProduct(){if(!productId){showError("ID produk tidak ditemukan.");return}try{const r=await fetch(API_URL,{method:"POST",body:JSON.stringify({action:"getProductDetail",product_id:productId})});const result=await r.json();if(result.status!=="success"||!result.product)throw new Error(result.message||"Produk tidak ditemukan.");currentProduct=result.product;renderProduct(result.product);bottomAction.classList.remove("hidden")}catch(e){showError(e.message||"Server tidak terhubung")}}
function showError(t){detailContent.classList.add("hidden");errorState.classList.remove("hidden");errorMessage.textContent=t}
function renderProduct(p){const images=Array.isArray(p.images)?p.images:[];const gallery=images.length?images.map((u,i)=>`<div class="gallery-item"><img src="${convertDriveImage(u)}" alt="${escapeHtml(p.nama_produk)} ${i+1}"></div>`).join(""):`<div class="gallery-placeholder">Foto produk tidak tersedia</div>`;const sellerName=p.seller?.username||p.seller?.nama_lengkap||"Penjual AdaAja";const sellerPhoto=convertDriveImage(p.seller?.foto_profile||"");detailContent.innerHTML=`<section class="gallery"><div class="gallery-track" id="galleryTrack">${gallery}</div><span class="gallery-counter" id="galleryCounter">1/${Math.max(images.length,1)}</span></section><section class="detail-section"><h1 class="product-title">${escapeHtml(p.nama_produk)}</h1><strong class="product-price">${formatRupiah(p.harga)}</strong><div class="product-meta"><span class="meta-chip primary">${escapeHtml(formatCondition(p.kondisi))}</span><span class="meta-chip">Stok ${Number(p.stok||0)}</span><span class="meta-chip">${escapeHtml(p.ship_from_region||"Lokasi belum tersedia")}</span></div></section><section class="detail-section"><div class="section-title"><h2>Deskripsi produk</h2></div><p class="product-description">${escapeHtml(p.deskripsi)}</p></section><section class="detail-section"><div class="section-title"><h2>Informasi produk</h2></div><div class="info-list"><div class="info-row"><span>Kategori</span><strong>${escapeHtml(p.category_id||"-")}</strong></div><div class="info-row"><span>Merek</span><strong>${escapeHtml(p.brand||"Tidak ada merek")}</strong></div><div class="info-row"><span>Biaya pengiriman</span><strong>${p.shipping_payer==="seller"?"Ditanggung penjual":"Ditanggung pembeli"}</strong></div><div class="info-row"><span>Metode pengiriman</span><strong>${escapeHtml(p.shipping_method||"-")}</strong></div><div class="info-row"><span>Waktu proses</span><strong>${escapeHtml(p.processing_time||"-")}</strong></div></div></section><section class="detail-section"><div class="section-title"><h2>Penjual</h2></div><a href="seller-profile.html?id=${encodeURIComponent(p.seller_id||"")}" class="seller-card"><div class="seller-avatar">${sellerPhoto?`<img src="${sellerPhoto}" alt="${escapeHtml(sellerName)}">`:escapeHtml(sellerName.charAt(0).toUpperCase())}</div><div class="seller-copy"><strong>${escapeHtml(sellerName)}</strong><span>Lihat profil dan produk penjual</span></div><span class="seller-chevron">›</span></a></section>`;document.title=`${p.nama_produk} - AdaAja`;document.getElementById("modalCurrentPrice").textContent=formatRupiah(p.harga);setupGallery()}
function setupGallery(){const t=document.getElementById("galleryTrack"),c=document.getElementById("galleryCounter");if(!t||!c)return;const total=t.children.length||1;t.addEventListener("scroll",()=>{const i=Math.round(t.scrollLeft/t.clientWidth)+1;c.textContent=`${Math.min(i,total)}/${total}`})}
document.getElementById("shareButton").onclick=async()=>{try{if(navigator.share)await navigator.share({title:currentProduct?.nama_produk||"Produk AdaAja",url:location.href});else{await navigator.clipboard.writeText(location.href);alert("Link produk disalin")}}catch{}};
document.getElementById("favoriteButton").onclick=e=>{if(!currentUser){location.href="login.html";return}e.currentTarget.classList.toggle("active")};
document.getElementById("offerButton").onclick=()=>{if(!currentUser){location.href="login.html";return}modalMessage.textContent="";offerPrice.value="";offerHint.textContent="";offerModal.classList.add("active")};
document.querySelectorAll("[data-close-modal]").forEach(x=>x.onclick=()=>offerModal.classList.remove("active"));
offerPrice.oninput=()=>{const raw=offerPrice.value.replace(/\D/g,"").slice(0,12);offerPrice.dataset.value=raw;offerPrice.value=raw?new Intl.NumberFormat("id-ID").format(Number(raw)):"";if(currentProduct&&raw){const d=Number(currentProduct.harga)-Number(raw);offerHint.textContent=d>0?`${formatRupiah(d)} lebih rendah dari harga sekarang`:"Harga penawaran harus lebih rendah"}else offerHint.textContent=""};
document.getElementById("submitOffer").onclick=()=>{const v=Number(offerPrice.dataset.value||0);if(!currentProduct||v<=0){modalMessage.textContent="Masukkan harga yang benar.";return}if(v>=Number(currentProduct.harga)){modalMessage.textContent="Penawaran harus lebih rendah dari harga saat ini.";return}modalMessage.textContent="Fitur penawaran akan aktif setelah database penawaran selesai."};
document.getElementById("buyButton").onclick=()=>{if(!currentUser){location.href="login.html";return}if(currentProduct)location.href=`checkout.html?id=${encodeURIComponent(currentProduct.product_id)}`};
loadProduct();
