const amountInput=document.getElementById("amountInput"),continueButton=document.getElementById("continueButton"),summaryAmount=document.getElementById("summaryAmount"),currentBalance=document.getElementById("currentBalance"),history=document.getElementById("topupHistory"),message=document.getElementById("pageMessage");
let selectedAmount=0,session=null;
const money=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const onlyDigits=v=>String(v||"").replace(/\D/g,"");
function setAmount(v){selectedAmount=Math.max(0,Math.floor(Number(v)||0));amountInput.value=selectedAmount?new Intl.NumberFormat("id-ID").format(selectedAmount):"";summaryAmount.textContent=selectedAmount?money(selectedAmount):"—";continueButton.disabled=selectedAmount<=0;document.querySelectorAll(".amount-chip").forEach(b=>b.classList.toggle("active",Number(b.dataset.amount)===selectedAmount))}
async function requireLogin(){const {data,error}=await window.adaajaSupabase.auth.getSession();if(error)throw error;session=data.session||null;if(!session?.user){localStorage.setItem("redirectAfterLogin","topup.html");location.replace("login.html");return null}return session}
async function loadWallet(){await window.adaajaSupabase.rpc("ensure_my_wallet");const {data,error}=await window.adaajaSupabase.from("user_wallets").select("available_balance,currency").eq("user_id",session.user.id).maybeSingle();if(error)throw error;currentBalance.textContent=data?money(data.available_balance):"—"}
function statusLabel(s){return({pending:"Menunggu",paid:"Berhasil",failed:"Gagal",expired:"Kedaluwarsa",cancelled:"Dibatalkan",refunded:"Refund"})[s]||s}
async function loadHistory(){const {data,error}=await window.adaajaSupabase.from("wallet_topups").select("id,topup_number,amount,status,created_at").eq("user_id",session.user.id).order("created_at",{ascending:false}).limit(5);if(error)throw error;if(!data?.length){history.innerHTML='<div class="history-empty">Belum ada riwayat Top Up.</div>';return}history.innerHTML=data.map(r=>`<div class="history-row"><span><strong>${r.topup_number}</strong><small>${new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(r.created_at))}</small></span><span class="history-amount"><strong>${money(r.amount)}</strong><span class="history-status ${r.status}">${statusLabel(r.status)}</span></span></div>`).join("")}
document.querySelectorAll(".amount-chip").forEach(b=>b.onclick=()=>setAmount(b.dataset.amount));amountInput.addEventListener("input",()=>setAmount(onlyDigits(amountInput.value)));
continueButton.onclick=async()=>{if(selectedAmount<=0||!session?.user)return;continueButton.disabled=true;message.className="page-message info";message.textContent="Membuat transaksi pembayaran...";try{const {data,error}=await window.adaajaSupabase.functions.invoke("adapay-topup-create",{body:{amount:selectedAmount}});if(error)throw error;if(!data?.redirect_url)throw new Error(data?.error||"Midtrans tidak mengembalikan halaman pembayaran.");location.href=data.redirect_url}catch(e){console.error(e);message.className="page-message error";message.textContent=e?.message||"Top Up belum dapat dibuat.";continueButton.disabled=false}}
(async()=>{try{await requireLogin();if(!session)return;await Promise.all([loadWallet(),loadHistory()])}catch(e){console.error(e);message.className="page-message error";message.textContent=e?.message||"Halaman Top Up belum dapat dimuat."}})();