const $ = (id) => document.getElementById(id);
const els = {
  available: $("availableBalance"), pending: $("pendingBalance"), income: $("lifetimeIncome"),
  withdrawn: $("withdrawnBalance"), currency: $("currencyLabel"), state: $("walletState"),
  stateText: $("walletStateText"), withdraw: $("withdrawButton"), withdrawHint: $("withdrawHint"),
  bankLabel: $("bankStatusLabel"), bankTitle: $("bankTitle"), bankSubtitle: $("bankSubtitle"),
  bankVerified: $("bankVerified"), withdrawal: $("withdrawalCard"), transactions: $("transactionList"),
  message: $("pageMessage"), refresh: $("refreshButton")
};
let currentSession=null,wallet=null,bank=null;

function money(v,c="IDR"){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("id-ID",{style:"currency",currency:c,maximumFractionDigits:0}).format(n):"—"}
function dateTime(v){const d=new Date(v);return v&&!Number.isNaN(d.getTime())?new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d):"—"}
function esc(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function mask(v){const s=String(v||"").replace(/\s/g,"");return !s?"":s.length<=4?s:`•••• ${s.slice(-4)}`}
async function requireLogin(){const {data,error}=await window.adaajaSupabase.auth.getSession();if(error)throw error;currentSession=data.session||null;if(!currentSession?.user){localStorage.setItem("redirectAfterLogin","wallet.html");location.replace("login.html");return null}return currentSession}

function renderWallet(data){
  wallet=data||null;
  if(!wallet){els.available.textContent=els.pending.textContent=els.income.textContent=els.withdrawn.textContent="—";els.currency.textContent="Wallet belum tersedia";els.state.className="wallet-state";els.stateText.textContent="Belum aktif";els.withdraw.disabled=true;els.withdrawHint.textContent="Saldo belum tersedia";return}
  const c=wallet.currency||"IDR";
  els.available.textContent=money(wallet.available_balance,c);els.pending.textContent=money(wallet.pending_balance,c);
  els.income.textContent=money(wallet.lifetime_income,c);els.withdrawn.textContent=money(wallet.withdrawn_balance,c);
  els.currency.textContent=`${c} · Saldo universal AdaPay`;
  const available=Number(wallet.available_balance||0);
  if(wallet.is_active===false||wallet.locked_at){els.state.className="wallet-state locked";els.stateText.textContent="Dibatasi";els.withdraw.disabled=true;els.withdrawHint.textContent=wallet.lock_reason||"Wallet sedang dibatasi";return}
  els.state.className="wallet-state active";els.stateText.textContent="Aktif";
  els.withdraw.disabled=!(available>0&&bank);
  els.withdrawHint.textContent=available<=0?"Saldo tersedia belum cukup":!bank?"Tambahkan rekening dahulu":"Cairkan ke rekening utama";
}
function renderBank(a){bank=a||null;if(!bank){els.bankLabel.textContent="REKENING BELUM ADA";els.bankTitle.textContent="Tambahkan rekening pencairan";els.bankSubtitle.textContent="Diperlukan untuk menarik saldo AdaPay.";els.bankVerified.hidden=true}else{els.bankLabel.textContent=bank.is_default?"REKENING UTAMA":"REKENING PENCAIRAN";els.bankTitle.textContent=bank.bank_name||bank.bank_code||"Rekening bank";els.bankSubtitle.textContent=[bank.account_holder_name,mask(bank.account_number)].filter(Boolean).join(" · ")||"Rekening tersimpan";els.bankVerified.hidden=!bank.is_verified}if(wallet)renderWallet(wallet)}
function statusInfo(s){return({requested:["Diajukan","warning"],pending:["Menunggu","warning"],approved:["Disetujui","warning"],processing:["Diproses","warning"],transferred:["Ditransfer","success"],completed:["Selesai","success"],rejected:["Ditolak","danger"],cancelled:["Dibatalkan","danger"]})[String(s||"").toLowerCase()]||[s||"Tidak diketahui",""]}
function renderWithdrawal(w){if(!w){els.withdrawal.innerHTML=`<div class="withdrawal-empty"><span class="empty-icon"><svg viewBox="0 0 24 24"><path d="M4 7h16v10H4z"></path><path d="M8 12h8"></path></svg></span><strong>Belum ada pencairan</strong><p>Permintaan pencairan terbaru akan tampil di sini.</p></div>`;return}const [label,cls]=statusInfo(w.status);els.withdrawal.innerHTML=`<div class="withdrawal-item"><div class="withdrawal-top"><div><small>Nominal pencairan</small><strong>${money(w.amount,wallet?.currency||"IDR")}</strong></div><span class="status-badge ${cls}">${esc(label)}</span></div><div class="withdrawal-meta"><span><small>Rekening tujuan</small><strong>${esc(w.bank_name||"Bank")} ${esc(mask(w.account_number))}</strong></span><span><small>Diajukan</small><strong>${esc(dateTime(w.requested_at||w.created_at))}</strong></span></div></div>`}
function txDirection(t){const type=String(t.transaction_type||"").toLowerCase();if(["topup","credit","income","release","sale","refund_credit"].some(x=>type.includes(x)))return"credit";if(["withdraw","debit","fee","purchase","refund_debit"].some(x=>type.includes(x)))return"debit";return Number(t.available_after||0)>Number(t.available_before||0)||Number(t.pending_after||0)>Number(t.pending_before||0)?"credit":Number(t.available_after||0)<Number(t.available_before||0)||Number(t.pending_after||0)<Number(t.pending_before||0)?"debit":"neutral"}
function txLabel(t){const type=String(t.transaction_type||"").toLowerCase();return({topup:"Top Up AdaPay",sale_pending:"Dana penjualan tertahan",sale_release:"Dana penjualan tersedia",purchase:"Pembayaran AdaPay",withdrawal:"Penarikan saldo",refund:"Refund",fee:"Biaya layanan",adjustment:"Penyesuaian saldo"})[type]||t.description||"Aktivitas AdaPay"}
function renderTransactions(rows){if(!rows?.length){els.transactions.innerHTML=`<div class="transaction-empty"><span class="empty-icon"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"></circle><path d="M12 7v5l3 2"></path></svg></span><strong>Belum ada transaksi AdaPay</strong><p>Top Up, pembayaran, refund, hasil penjualan, dan pencairan akan tampil di sini.</p></div>`;return}els.transactions.innerHTML=rows.map(t=>{const dir=txDirection(t),prefix=dir==="credit"?"+":dir==="debit"?"−":"",icon=dir==="credit"?'<path d="M12 19V7"></path><path d="m7 12 5-5 5 5"></path>':dir==="debit"?'<path d="M12 5v12"></path><path d="m7 12 5 5 5-5"></path>':'<circle cx="12" cy="12" r="9"></circle><path d="M12 7v5l3 2"></path>';return`<div class="transaction-row"><span class="transaction-icon ${dir}"><svg viewBox="0 0 24 24">${icon}</svg></span><span class="transaction-copy"><strong>${esc(txLabel(t))}</strong><span>${esc(t.transaction_number||t.reference_type||"AdaPay")}</span></span><span class="transaction-amount"><strong class="${dir}">${prefix}${money(Math.abs(Number(t.amount||0)),wallet?.currency||"IDR")}</strong><small>${esc(dateTime(t.created_at))}</small></span></div>`}).join("")}

async function loadWallet(uid){await window.adaajaSupabase.rpc("ensure_my_wallet");const {data,error}=await window.adaajaSupabase.from("user_wallets").select("*").eq("user_id",uid).maybeSingle();if(error)throw error;renderWallet(data)}
async function loadBank(uid){const {data,error}=await window.adaajaSupabase.from("seller_bank_accounts").select("*").eq("seller_id",uid).order("is_default",{ascending:false}).order("created_at",{ascending:true}).limit(1).maybeSingle();if(error)throw error;renderBank(data)}
async function loadWithdrawal(uid){const {data,error}=await window.adaajaSupabase.from("withdrawals").select("id,amount,status,bank_name,account_number,requested_at,created_at").eq("seller_id",uid).order("requested_at",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;renderWithdrawal(data)}
async function loadTransactions(uid,limit=6){const {data,error}=await window.adaajaSupabase.from("user_wallet_transactions").select("*").eq("user_id",uid).order("created_at",{ascending:false}).limit(limit);if(error)throw error;renderTransactions(data)}
async function loadPage(){els.message.className="page-message";els.message.textContent="";els.refresh.disabled=true;try{const s=await requireLogin();if(!s)return;const uid=s.user.id;await loadWallet(uid);await loadBank(uid);await Promise.all([loadWithdrawal(uid),loadTransactions(uid)])}catch(e){console.error(e);els.message.textContent=e?.message||"Data AdaPay belum dapat dimuat.";els.message.className="page-message error"}finally{els.refresh.disabled=false}}
els.withdraw.onclick=()=>{if(!els.withdraw.disabled)location.href="withdraw.html"};$("historyButton").onclick=()=>$("transactionSection").scrollIntoView({behavior:"smooth"});$("seeAllTransactions").onclick=async()=>{if(currentSession?.user)await loadTransactions(currentSession.user.id,50)};els.refresh.onclick=loadPage;window.adaajaSupabase.auth.onAuthStateChange((e,s)=>{currentSession=s||null;if(e==="SIGNED_OUT")location.replace("login.html")});loadPage();